org: idcode
app: aws-lamda-node
service: aws-lamda-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:589273066424:table/TaskTable

functions:
  hello:
    handler: src/hellow.hello
    events:
      - httpApi:
          path: /
          method: get
  getTasks:
    handler: src/getTasks.getTasks
    events:
      - httpApi:
          path: /tasks
          method: get
  getTask:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /task/{id}
          method: get
  createTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /task
          method: post
  updateTask:
    handler: src/updateTask.updateTask
    events:
      - httpApi:
          path: /task/{id}
          method: put
  deleteTask:
    handler: src/deleteTask.deleteTask
    events:
      - httpApi:
          path: /task/{id}
          method: delete

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
